apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace 'com.animeworld.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.animeworld.app"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "2.0.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.webkit:webkit:1.10.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.9.22"
    implementation "com.capacitorjs:core:6.0.0"
}
